### ISSUE TITLE
convert to python3

### ISSUE THREAD

**Issue by perestoronin** [bnoordhuis/gyp#1]
Need convert input.py to py3k

**Comment by pavel-i-am** [comment]
It isn't just input.py that is incompatible with py3k here. Please confirm strictly this file or all of them so I can know what to focus on. Thanks.

**Comment by ghost** [comment]
I've written a similar request to node and have actually generated the python3 compatibility for them.  They indicated to me that it isn't worth it because `gyp` currently doesn't support python3.  I believe they would be willing to support python3 if  `gyp` did.  That would mean tools like `nexe` would be able to work on arch.

If you want I can do the conversion and give you a merge request.  I have useful vim tools ready to go.

**Comment by RavenX8** [comment]
it would be nice if this happened soon since python2.7 EOL is in 2020.
